repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.10
    hooks:
      # Run linter
      - id: ruff-check
        args: [--fix] # auto-fixes, but aborts commit if changes made
      # Run formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2 # check for latest version
    hooks:
      - id: mypy
        additional_dependencies: [fastapi, pydantic, types-requests]
