services:
  # Container running the FastAPI image
  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: weather_api
    ports:
      - "8000:${APP_PORT}"
    volumes:
      - "./src:/code"
    env_file:
      - "./.env"
    depends_on:
      db:
        condition: service_healthy

  # PostgreSQL container
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-weather_locations} # "weather_locations" as default
      POSTGRES_USER: ${POSTGRES_USER:-postgres} # "postgres" as default
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres} # "postgres" as default
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - "./.env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 3s
      retries: 3
    
volumes:
  postgres_data:
