"""2025_09_02_14_50_Add forecasts table

Revision ID: a35eebc89049
Revises: 0687a8dd6f8e
Create Date: 2025-09-02 14:50:41.212894

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a35eebc89049"
down_revision: Union[str, Sequence[str], None] = "0687a8dd6f8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecasts",
        sa.Column("forecast_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("forecast_date", sa.DateTime(), nullable=False),
        sa.Column("min_forecasted", sa.Integer(), nullable=False),
        sa.Column("max_forecasted", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"], ["locations.location_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("forecast_id"),
        sa.UniqueConstraint(
            "location_id", "forecast_date", name="unique_location_date_constraint"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forecasts")
    # ### end Alembic commands ###
